-- MySQL Script generated by MySQL Workbench
-- пт, 09-лис-2018 14:15:16 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `passworldHash` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `idVideo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `duration` TIME NULL,
  `rating` TINYINT(4) NULL,
  `url` VARCHAR(200) NULL,
  PRIMARY KEY (`idVideo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `idGroups` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `type` CHAR(1) NOT NULL,
  PRIMARY KEY (`idGroups`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Video` (
  `Users_idUsers` INT UNSIGNED NOT NULL,
  `Video_idVideo` INT UNSIGNED NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Video_idVideo`),
  INDEX `fk_Users_has_Video_Video1_idx` (`Video_idVideo` ASC),
  INDEX `fk_Users_has_Video_Users_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Users_has_Video_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Video_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video_has_Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video_has_Groups` (
  `Video_idVideo` INT UNSIGNED NOT NULL,
  `Groups_idGroups` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Video_idVideo`, `Groups_idGroups`),
  INDEX `fk_Video_has_Groups_Groups1_idx` (`Groups_idGroups` ASC),
  INDEX `fk_Video_has_Groups_Video1_idx` (`Video_idVideo` ASC),
  CONSTRAINT `fk_Video_has_Groups_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Video_has_Groups_Groups1`
    FOREIGN KEY (`Groups_idGroups`)
    REFERENCES `mydb`.`Groups` (`idGroups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
