-- MySQL Script generated by MySQL Workbench
-- пт, 09-лис-2018 13:00:34 +0200
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kursova
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kursova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kursova` DEFAULT CHARACTER SET utf8;
USE `kursova` ;
ALTER SCHEMA `kursova`  DEFAULT COLLATE utf8_unicode_ci ;

-- -----------------------------------------------------
-- Table `kursova`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursova`.`Users` (
  `idUsers` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `login` VARCHAR(45) NOT NULL UNIQUE,
  `passworldHash` VARCHAR(100) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsers`)
  ) ENGINE = InnoDB
	PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `kursova`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursova`.`Video` (
  `idVideo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `duration` TIME NULL,
  `rating` TINYINT(4) NOT NULL DEFAULT 5 CHECK(`rating` >= 1 AND `rating` <= 10),
  `url` VARCHAR(200) NULL,
  PRIMARY KEY (`idVideo`)
  ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursova`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursova`.`Groups` (
  `idGroups` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(80) NOT NULL,
  `type` CHAR(1) NOT NULL,
  PRIMARY KEY (`idGroups`),
  CONSTRAINT `typeGroup` CHECK(`type` IN ('y', 'g', 'd', 'a', 'o')) # year, genre, director, actor, other
  ) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursova`.`Users_has_Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursova`.`Users_has_Video` (
  `Users_idUsers` INT UNSIGNED NOT NULL,
  `Video_idVideo` INT UNSIGNED NOT NULL,
  `status` CHAR(1) NOT NULL,
  PRIMARY KEY (`Users_idUsers`, `Video_idVideo`),
  INDEX `fk_Users_has_Video_Video1_idx` (`Video_idVideo` ASC),
  INDEX `fk_Users_has_Video_Users_idx` (`Users_idUsers` ASC),
  CONSTRAINT `fk_Users_has_Video_Users`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `kursova`.`Users` (`idUsers`),
  CONSTRAINT `fk_Users_has_Video_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `kursova`.`Video` (`idVideo`),
    CONSTRAINT `typeStatus` CHECK(`status` IN ('c', 'h', 's')) #completed, happens, scheduled
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kursova`.`Video_has_Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kursova`.`Video_has_Groups` (
  `Video_idVideo` INT UNSIGNED NOT NULL,
  `Groups_idGroups` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`Video_idVideo`, `Groups_idGroups`),
  INDEX `fk_Video_has_Groups_Groups1_idx` (`Groups_idGroups` ASC),
  INDEX `fk_Video_has_Groups_Video1_idx` (`Video_idVideo` ASC),
  CONSTRAINT `fk_Video_has_Groups_Video1`
    FOREIGN KEY (`Video_idVideo`)
    REFERENCES `kursova`.`Video` (`idVideo`),
  CONSTRAINT `fk_Video_has_Groups_Groups1`
    FOREIGN KEY (`Groups_idGroups`)
    REFERENCES `kursova`.`Groups` (`idGroups`)
    ) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `kursova`.`log` (
  `idLog` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `logMessage` VARCHAR(200) NOT NULL,
  `tableName` VARCHAR(20),
  `idRowsTable` INT UNSIGNED NOT NULL,
  `actionType` CHAR(1) CHECK (`actionType` IN ('i', 'u', 'd')), # insert, update, delete
  `time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idLog`)
) ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
